# Generated by Django 3.1.1 on 2021-04-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_pedal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guitar',
            old_name='name',
            new_name='model',
        ),
    ]
